spring:
  datasource:
    url: jdbc:mysql://localhost:3306/featureconfig?characterEncoding=utf8&useSSL=false
    username: root
    password: '12345678'
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML
    cache: false
server:
  port: 80
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: me.wang.featureconfig.mapper
